---
title: "01_vaccine_coverage"
author: "Henry Cooksley"
date: "14/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)
```

Read in the latest xlsx file
```{r}
path <- "COVID-19-weekly-announced-vaccinations-01-July-2021-revised-.xlsx"
sheets <- (readxl::excel_sheets(path))
print(sheets)
```

Extract the first dose table from the sheet
```{r}
total_first_dose_tbl <- readxl::read_excel(path, sheet = "NHS Region") %>% 
  dplyr::slice(11:12) %>% 
  dplyr::select(3:16) # change this if the columns change!

# sanity check
stopifnot(total_first_dose_tbl[[1]][1] == "Under 18")
stopifnot(total_first_dose_tbl[[14]][1] == "80+")
stopifnot(nrow(total_first_dose_tbl) == 2)

total_first_dose_tbl
```

Extract the second dose table from the sheet
```{r}
total_second_dose_tbl = readxl::read_excel(path, sheet = "NHS Region") %>% 
  dplyr::slice(11:12) %>% 
  dplyr::select(20:33) # change this if the columns change!

# sanity check
stopifnot(total_second_dose_tbl[[1]][1] == "Under 18")
stopifnot(total_second_dose_tbl[[14]][1] == "80+")
stopifnot(nrow(total_second_dose_tbl) == 2)

total_second_dose_tbl
```

Tidy first dose table
```{r}
names(total_first_dose_tbl) <- lapply(total_first_dose_tbl[1, ], as.character)

total_first_dose_tbl <- dplyr::slice(total_first_dose_tbl, 2) %>%
  tidyr::pivot_longer(cols = everything(), names_to = "age", values_to = "first_dose")

# lock in factor level order
total_first_dose_tbl$age <- factor(total_first_dose_tbl$age, levels = total_first_dose_tbl$age)

# cast to numeric
total_first_dose_tbl$first_dose <- as.numeric(total_first_dose_tbl$first_dose)

total_first_dose_tbl
```

Tidy second dose table
```{r}
names(total_second_dose_tbl) <- lapply(total_second_dose_tbl[1, ], as.character)

total_second_dose_tbl <- dplyr::slice(total_second_dose_tbl, 2) %>%
  tidyr::pivot_longer(cols = everything(), names_to = "age", values_to = "second_dose")

# lock in factor level order
total_second_dose_tbl$age <- factor(total_second_dose_tbl$age, levels = total_second_dose_tbl$age)

# cast to numeric
total_second_dose_tbl$second_dose <- as.numeric(total_second_dose_tbl$second_dose)

total_second_dose_tbl
```

Join first and second dose table
```{r}
total_both_doses_tbl <- total_first_dose_tbl %>% left_join(total_second_dose_tbl, by = "age")
total_both_doses_tbl <- reshape2::melt(total_both_doses_tbl, id.vars = c("age"), variable.name = "dose", value.name = "total")
total_both_doses_tbl
```

Convert total to millions of doses
```{r}
total_both_doses_tbl$total_millions <- total_both_doses_tbl$total / 1e6
total_both_doses_tbl
```

Extract the percent first doses table
```{r}
percent_dose_1_tbl <- readxl::read_excel(path, sheet = "NHS Region") %>% 
  dplyr::slice(11:12) %>% 
  dplyr::select(39:51)

# sanity check
stopifnot(percent_dose_1_tbl[[1]][1] == "18-24")
stopifnot(percent_dose_1_tbl[[13]][1] == "80+")
stopifnot(nrow(percent_dose_1_tbl) == 2)

percent_dose_1_tbl
```

Clean percent first doses table
```{r}
names(percent_dose_1_tbl) <- percent_dose_1_tbl %>% dplyr::slice(1) %>% unlist(., use.names = FALSE)
percent_dose_1_tbl <- percent_dose_1_tbl %>% dplyr::slice(2)
percent_dose_1_tbl <- percent_dose_1_tbl %>% pivot_longer(cols = everything(), names_to = "age", values_to = "percent_dose_1")
percent_dose_1_tbl$percent_dose_1_measure <- stringr::str_replace_all(percent_dose_1_tbl$percent_dose_1, "100%\\*", "1.00") %>%
  as.numeric * 10.0 # this is for the ggplot axis to work correctly
percent_dose_1_tbl
```




Set DHSC colours and plot data
```{r}
# Set DHSC colours
dhsc_primary_0 <- "#00ad93"
dhsc_primary_5 <- "#99ded4"

# Plot data
ggplot2::ggplot(data = NULL) + 
  geom_col(data = total_both_doses_tbl, aes(age, total_millions, fill = dose), position = "dodge2") + 
  scale_fill_manual(name = "", labels = c("1st dose", "2nd dose"), 
                    values = c(dhsc_primary_5, dhsc_primary_0)) + 
  theme_minimal() + 
  theme(legend.position = "top", legend.text = element_text(size = 8), legend.key.size = unit(0.4, 'cm')) + 
  xlab("") + 
  ylab("millions") +
  geom_point(data = percent_dose_1_tbl, aes(age, percent_dose_1_measure), shape = 5) +
  scale_y_continuous(limits = c(0, 10), breaks = c(0:10), minor_breaks = NULL, sec.axis = sec_axis(trans = ~ . * 0.1, breaks = seq(0, 1, 0.1), labels = scales::percent_format(1)))
```

